### ISSUE TITLE
Remove Markdig sourcecode from your repository

### ISSUE THREAD

**Issue by xoofx** [water-air-flash/MarkdownEditor.Net#1]
Hi,
could you remove the Markdig sourcecode from your repository and link to the nuget package instead?
(when I search projects using Markdig, I found this repo but it is actually copying all of it)
Thanks

**Comment by water-air-flash** [comment]
@xoofx I'm very sorry for inappropriately copy it into my repository and have replaced it with library reference.the Markdig package is very wonderful let me want to have a better understanding and make some adjustment to better fit my work.sorry，English is not my native language ^^!!!
